<a href="https://colab.research.google.com/github/akuponiyi/My_NoteBook/blob/main/OmobolanleOluwatayo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#dimensional arrays
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
#2 dimension
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
#3 dimension
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
#3 dimension
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])
arr3.shape

(3, 2, 3)

In [9]:
arr4 = np.sort([2,4,6,1,3,5])
arr4

array([1, 2, 3, 4, 5, 6])

In [12]:
arr4 = np.arange(10,50,3)
arr4

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [14]:
a = np.arange(6)
a
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
a = np.array([1,2,3,4,5,6])
a.shape
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [17]:
data = np.array([1,2,3])
data[1]

2

In [18]:
data = np.array([1,2,3])
data[0:2]

array([1, 2])

In [23]:
a = np.array([1,2,3,4,5,6,7,8,9])
arr1 = a[2:8]
c = a[(a>2)&(a<9)]
c

array([3, 4, 5, 6, 7, 8])

In [26]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[4,5,6],[7,8,9]]])
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0, 1, 1, 1, 2]),
 array([0, 0, 0, 1, 1, 1, 1, 0]),
 array([0, 1, 2, 0, 0, 1, 2, 0]))

In [30]:
data = np.array([1,2])
ones = np.ones (2,dtype=int)
data + ones

array([2, 3])

In [31]:
data = np.array([1,2])
ones = np.ones (2,dtype=int)
data * ones

array([1, 2])

In [32]:
data = np.array([1,2])
ones = np.ones (2,dtype=int)
data / ones

array([1., 2.])

In [41]:
a = np.array([1,2,3,4,5])
a.std()


1.4142135623730951